services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - eureka__client__serviceUrl=http://eureka-server:8761/eureka/
    networks:
      - microservices-network

networks:
  microservices-network:
    external: true