version: '3.8'

services:
  eureka-server:
    image: steeltoeoss/eureka-server
    ports:
      - "8761:8761"
    environment:
      EUREKA_CLIENT_REGISTERWITH_EUREKA: "false"
      EUREKA_CLIENT_FETCHREGISTRY: "false"
      EUREKA_SERVER_ENABLESELFPRESERVATION: "true"
      EUREKA_SERVER_EVICTIONINTERVALTIMERINMS: "5000"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    container_name: keycloak
    ports:
      - "2000:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev

networks:
  default:
    external:
      name: microservices-network